repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: requirements-txt-fixer
    files: ^(requirements.*\.txt)$
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: name-tests-test
    files: ^tests\/test_(unit|integration)\/.*\.py$
    args: [--django]
  - id: trailing-whitespace
  - id: detect-private-key
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: remove-tabs
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [-w]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    files: setuptools_git_versioning.py
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: text-unicode-replacement-char
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
  hooks:
  - id: blacken-docs
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
  - id: mypy
    additional_dependencies: [types-six, types-toml]
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.5
  hooks:
  - id: python-bandit-vulnerability-check
    # TODO: remove line below after https://github.com/PyCQA/bandit/issues/488
    args: [-lll, --recursive, -x, './venv/*,./tests/,./pytest_cache/*', .]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
