name: Automerge

on:
  pull_request:

jobs:
  automerge:
    name: Enable pull request automerge
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]' || github.event.pull_request.user.login == github.repository_owner

    steps:
    - uses: alexwilson/enable-github-automerge-action@1.0.0
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        merge-method: REBASE

  autoapprove:
    name: Automatically approve pull request
    needs: [automerge]
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]' || github.event.pull_request.user.login == github.repository_owner

    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
