name: Releases

on:
  push:
    tags:
    - v*

jobs:
  wait-tests:
    name: Wait for tests
    runs-on: ubuntu-latest

    steps:
    - uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-tests
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Tests done
        ref: ${{ github.sha }}
        timeoutSeconds: 3600

    - name: Fail the Build
      uses: cutenode/action-always-fail@v1
      if: steps.wait-for-tests.outputs.conclusion != 'success'

  wait-codeql:
    name: Wait for CodeQL
    runs-on: ubuntu-latest

    steps:
    - uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-codeql
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: Analyze
        ref: ${{ github.sha }}
        timeoutSeconds: 3600

    - name: Fail the Build
      uses: cutenode/action-always-fail@v1
      if: steps.wait-for-codeql.outputs.conclusion != 'success'

  release:
    name: Release package
    runs-on: ubuntu-latest
    needs: [wait-tests, wait-codeql]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-3.10-release-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-3.10-release-${{ hashFiles('requirements*.txt') }}
          ${{ runner.os }}-python-3.10-tests-${{ hashFiles('requirements*.txt') }}
          ${{ runner.os }}-python-3.10-codeql-${{ hashFiles('requirements*.txt') }}
          ${{ runner.os }}-python-3.10-release-
          ${{ runner.os }}-python-3.10-tests-
          ${{ runner.os }}-python-3.10-codeql-
          ${{ runner.os }}-python
          ${{ runner.os }}-

    - name: Upgrade pip
      run: python -m pip install --upgrade pip setuptools wheel twine

    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-doc.txt

    - name: Build package
      run: python setup.py bdist_wheel

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.x

    - name: Build release notes
      run: |
        mkdir reports/
        pip install -e . --no-build-isolation
        version=$(echo $GITHUB_REF_SLUG | sed -E "s/v(.*)/\1/")
        changelog generate-md -c ./docs/conf.py CHANGELOG.rst -v $version > reports/release.md

    - name: Check package
      run: twine check dist/*

    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --skip-existing dist/*

    - name: Create Github release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body_path: reports/release.md
        files: |
          dist/*
